newname is now fully functional and supports 2 options and integration with other scripts

diff --git a/bb_submission_organizer/newname b/bb_submission_organizer/newname
--- a/bb_submission_organizer/newname
+++ b/bb_submission_organizer/newname
@@ -8,14 +8,16 @@ index number is appended to the destination name.
 # Print proper usage message to console. 
 function show_usage() {
 
-    echo "TARGET_PATH and DESTINATION_PATH are required."
-    echo "Usage: newname [-q quiet] [-d debug] TARGET_PATH DESTINATION_PATH"
+    echo "Usage: newname SOURCE DESTINATION"
+    echo "  or: newname [OPTION]... TARGET_PATH DESTINATION_PATH"
+    echo "  or: newname SOURCE DESTINATION [OPTION]..."
+    printf "\nSOURCE and DESTINATION are required arguments.\n"
 
     # Show accepted optional arguments
     if [[ $1 == "options" ]]; then
-        echo "  Available options:"
-        echo "    -q    Quiet mode: limited shell output and error messages."
-        echo "    -D    Debug mode: Extended shell output (logs, warnings, errors)."
+        printf "\nOptions:\n"
+        printf "\t-q\tQuiet mode: limited shell output and error messages.\n"
+        printf "\t-D\tDebug mode: Extended shell output (logs, warnings, errors).\n"
     fi
     # End script after displaying help message
     exit
@@ -26,7 +28,7 @@ function show_usage() {
 # param 2: (optional) String to echo
 function throw_error() {
 
-    echo "Error ($1)"
+    printf "\nnewname: Error($1): "
 
     # If quiet mode is enabled, exit without detailed error message
     if [[ options_enabled[$O_QUIET] -eq 1 ]]; then
@@ -34,20 +36,20 @@ function throw_error() {
     fi
 
     case $1 in
-    1)  echo "Insufficient number of arguments."
+    1)  printf "Insufficient number of arguments.\n"
         show_usage
         ;;
-    2)  echo "Unexpected argument: $2"
+    2)  printf "Unexpected argument: $2\n"
         show_usage
         ;;
-    3)  echo "Invalid argument: $2"
+    3)  printf "Invalid argument: $2\n"
         show_usage "options"
         ;;
-    4)  echo "Target file \"$2\" does not exist."
+    4)  printf "Target/source file \"$2\" does not exist.\n"
         ;;
-    5)  echo "mv command exited unexpectedly with code $2"
+    5)  printf "mv operation exited unexpectedly.\n"
         ;;
-    *)  echo "An unkown error occured: $1"
+    *)  printf "An unkown error occured: $1\n"
         ;;
     esac
 
@@ -70,20 +72,24 @@ OPTIONS[O_DEBUG]="-D"
 # Array with values indicating if an option at the corresponding index is enabled
 options_enabled=()
 
+# Options that are passed to mv command (-v or none depending on this script's mode)
+mv_options=""
+
 # All options disabled by default (ininitialized in a loop for scalability of options)
 for (( i=0; i<${#OPTIONS[@]}; i++ )); do
     options_enabled[i]=0
 done
 
 function handle_options() {
-
     # Check argument against accepted options
     for (( i=0; i<${#OPTIONS[@]}; i++ )); do
         # If argument matches an options string, set the option to enabled
         if [[ $1 == ${OPTIONS[i]} ]]; then
             options_enabled[i]=1
             if [[ $i -eq O_DEBUG ]]; then
-                echo "Debug mode enabled..."
+                echo "newname: Debug mode enabled."
+                # Run mv commands with "verbose" option
+                mv_options="-v"
             fi
             return
         fi
@@ -101,8 +107,13 @@ target=""
 destination=""
 # Array of option arguments passed
 
+# If arg 1 is "--help", show usage information and exit.
+if [[ $1 == "--help" ]]; then
+    show_usage "options"
+fi
+
 # Get options from command-line arguments if they are present.
-# Option arguments must be 1 character starting with a '-' (hyphen)
+# Option arguments must start a '-'. Valid options are shown in usage info.
 if [[ $# -eq 2 ]]; then
     # Get target path from argument 1
     target=$1
@@ -111,23 +122,21 @@ if [[ $# -eq 2 ]]; then
 
 elif [[ $# -gt 2 ]]; then
     # Arguments starting with '-' are handled as options
-    i=0
     for arg in $@; do
-        if [[ $arg =~ \- ]]; then
+        if [[ ${arg:0:1} == '-' ]]; then
             handle_options $arg
-            continue
-        else [[ ! $arg =~ \- ]]
+        else
             if [[ -z $target ]]; then
                 # First argument not starting with '-' is expected to be TARGET
                 target=$arg
                 if [[ options_enabled[O_DEBUG] -eq 1 ]]; then
-                    echo "TARGET path set to: $target"
+                    echo "newname: TARGET path set to: $target"
                 fi
             elif [[ -z $destination ]]; then
                 # TARGET already assigned, arg is expected to be DESTINATION
                 destination=$arg
                 if [[ options_enabled[O_DEBUG] -eq 1 ]]; then
-                    echo "DESTINATION path set to: $destination"
+                    echo "newname: DESTINATION path set to: $destination"
                 fi
             else
                 # Extra, unexpected argument after destination (not an option)
@@ -139,24 +148,23 @@ else
     # Insufficient number of arguments (less than 2)
     throw_error 1
 fi
-
 # Error (4): Target file does not exist.
 if [[ ! -e "$target" ]]; then
-    throw_error 4 "$target"  
+    throw_error 4 "$target"
 fi
 
 # Check if destination path already exists
 if [[ ! -e "$destination" ]]; then
     # Destination path does NOT exist, rename target file as normal.
-    mv $target $destination
+    mv $mv_options "$target" "$destination"
 
-    if [ ! $? -eq 0 ]; then
+    if [[ $? -ne 0 ]]; then
         # mv command failed and returned an error code
-        throw_error 5 $?
+        throw_error 5
     fi
 
     if [[ ${options_enabled[O_DEBUG]} -eq 1 ]]; then
-        echo "File \"$target\" was successfully renamed to \"$destination\""
+        echo "newname: File \"$target\" was successfully renamed to \"$destination\""
     fi
 else
     : 'File name already exists. Increment and append the 
@@ -167,23 +175,23 @@ else
     index=0
     new_path=$destination
 
-    while [ -e $new_path ]; do
+    while [[ -e $new_path ]]; do
         let index++
         new_path="$destination.$index"
     done
 
     if [[ ${options_enabled[O_QUIET]} -eq 0 ]]; then
-        echo "File \"$destination\" already exists:"
+        echo "newname: File \"$destination\" already exists:"
     fi
 
-    mv $target $new_path
+    mv $mv_options "$target" "$new_path"
 
-    if [ ! $? -eq 0 ]; then
+    if [[ $? -ne 0 ]]; then
         # mv command failed and returned an error code
         throw_error 5
     fi
 
     if [[ ${options_enabled[O_QUIET]} -eq 0 ]]; then
-        echo "\"$target\" was renamed to \"$new_path\"."
+        echo "newname: \"$target\" was renamed to \"$new_path\"."
     fi
 fi
